#个人信息表
DROP TABLE "PERSON";

CREATE TABLE "PERSON" (
  "ID" BIGINT NOT NULL,
  "NAME" VARCHAR(20) DEFAULT NULL,
  "SEX" VARCHAR(4) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

INSERT INTO "PERSON" ("ID", "NAME", "SEX") VALUES (1,'孙悟空','男');
INSERT INTO "PERSON" ("ID", "NAME", "SEX") VALUES (2,'猪八戒','男');
INSERT INTO "PERSON" ("ID", "NAME", "SEX") VALUES (3,'沙悟净','男');